site_name: Smolecki Park Łuczniczy

site_url: https://smoleckiparkluczniczy.pl
theme:
  icon:
    logo: material/bow-arrow
    favicon: material/bow-arrow
  name: material
  palette:
    primary: green
    accent: green
  font:
    text: Source Sans Pro
  language: pl
  features:
    - navigation.tabs
    - navigation.path
    - navigation.prune

nav:
  - 'Home': index.md
  - 'Wspracie finansowe': crowdfunding.md
  - 'Kontakt': contact.md

extra:
  analytics:
    provider: google
    property: G-CZBYDQ2SBQ
    feedback:
        title: Was this page helpful?
        ratings:
          - icon: material/emoticon-happy-outline
            name: This page was helpful
            data: 1
            note: >-
              Thanks for your feedback!
          - icon: material/emoticon-sad-outline
            name: This page could be improved
            data: 0
            note: >- 
              Thanks for your feedback!
  consent:
    title: Dbamy o Twoją prywatność
    description: >- 
      Używamy plików cookie również do rozpoznawania Twoich powtarzających się wizyt i preferencji
      co do pomiaru efektywności naszej storny i tego, czy użytkownicy znaleźć to, czego szukają. Za Twoją zgodą pomagasz nam ulepszyć naszą stronę.
    actions:
      - accept
      - manage

plugins:
  - search

extra_css:
  - stylesheets/extra.css
