site_name: Smolecki Park Łuczniczy

site_url: https://smoleckiparkluczniczy.pl
theme:
  favicon: assets/icon.png
  logo: assets/logo.png
  name: material
  palette:
    primary: green
    accent: green
  font:
    text: Source Sans Pro
  language: pl
  features:
    - navigation.tabs
    - navigation.path
    - navigation.prune

nav:
  - 'Home': index.md
  - 'Wspracie finansowe': crowdfunding.md
  - 'Kontakt': contact.md

extra:
#  generator: false
  social:
    - icon: material/facebook
      link: https://www.facebook.com/uksluks
  analytics:
    provider: google
    property: G-CZBYDQ2SBQ
    feedback:
        title: Czy ta strona była pomocna?
        ratings:
          - icon: material/thumb-up-outline
            name: Ta strona okazała się pomocna
            data: 1
            note: >-
              Thanks for your feedback!
          - icon: material/thumb-down-outline
            name: Tę stronę można ulepszyć
            data: 0
            note: >- 
              Thanks for your feedback!
  consent:
    title: Dbamy o Twoją prywatność
    description: >- 
      Używamy plików cookie również do rozpoznawania Twoich powtarzających się wizyt i preferencji
      co do pomiaru efektywności naszej storny i tego, czy użytkownicy znaleźć to, czego szukają. Za Twoją zgodą pomagasz nam ulepszyć naszą stronę.
    actions:
      - accept
      - manage

plugins:
  - search

extra_css:
  - stylesheets/extra.css
