site_name: Smolecki Park Łuczniczy
site_description: Smolecki Park Łuczniczy - Archery Park Smolec. Strona internetowa parku łuczniczego w Smolcu. Arena dla łucznictwa olimpijskiego oraz biegowego (run archery). Wspieraj naszą inicjatywę!
site_url: https://smoleckiparkluczniczy.pl

copyright: Copyright &copy; 2024 UKS Luks Smolec

theme:
  favicon: assets/icon.png
  logo: assets/logo.png
  name: material
  custom_dir: overrides
  palette:
    primary: green
    accent: green
  font:
    text: Source Sans 3
  language: pl
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.indexes

nav:
  - 'Home': index.md
  - 'Projekt': project.md
  - 'Aleja Łuczników':
    - avenue.md
    - archers.md
  - 'Wspracie finansowe': crowdfunding.md
  - Blog:
    - blog/index.md
  - Kontakt: contact.md

extra:
  social:
    - icon: material/home
      link: https://uksluks.pl
    - icon: material/facebook
      link: https://www.facebook.com/archeryparksmolec/
    - icon: material/instagram
      link: https://www.instagram.com/smoleckiparkluczniczy/
    - icon: material/rss-box
      link: feed_json_created.json
    - icon: material/robot
      link: https://stats.uptimerobot.com/u3PRmM31ye/797062699
  analytics:
    provider: google
    property: G-CZBYDQ2SBQ
  consent:
    title: Dbamy o Twoją prywatność
    description: >- 
      Używamy plików cookie również do rozpoznawania Twoich powtarzających się wizyt i preferencji
      co do pomiaru efektywności naszej storny i tego, czy użytkownicy znaleźć to, czego szukają. Za Twoją zgodą pomagasz nam ulepszyć naszą stronę.
    actions:
      - accept
      - manage

plugins:
  - search
  - blog:
      pagination_per_page: 5
      draft_on_serve: false
      draft_if_future_date: true
      blog_toc: true
  - tags:
      tags_file: tags.md
  - glightbox:
      zoomable: true
      effect: zoom
      touchNavigation: true
  - rss:
      match_path: blog/.*
      date_from_meta:
        as_creation: date
      use_git: false
  - social
  - autorefs:
      resolve_closest: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
