site_name: Smolecki Park Łuczniczy

site_url: https://smoleckiparkluczniczy.pl
theme:
  icon:
    logo: material/bow-arrow
    favicon: material/bow-arrow
  name: material
  palette:
    primary: green
    accent: green
  font:
    text: Source Sans Pro
  language: pl
  features:
    - navigation.tabs
    - navigation.path
    - navigation.prune

nav:
  - 'Home': index.md
  - 'Kontakt': contact.md

extra:
  consent:
    title: Dbamy o Twoją prywatność
    description: >- 
      Używamy plików cookie również do rozpoznawania Twoich powtarzających się wizyt i preferencji
      co do pomiaru efektywności naszej dokumentacji i tego, czy użytkownicy
      znaleźć to, czego szukają. Za Twoją zgodą pomagasz nam ulepszyć naszą stronę.
    actions:
      - accept
      - manage

plugins:
  - search

extra_css:
  - stylesheets/extra.css
