site_name: Smolecki Park Łuczniczy

site_description: Smolecki Park Łuczniczy - Archery Park Smolec. Strona internetowa parku łuczniczego w Smolcu. Arena dla łucznictwa olimpijskiego oraz biegowego (run archery). Wspieraj naszą inicjatywę!
site_url: https://smoleckiparkluczniczy.pl

copyright: Copyright &copy; 2024 UKS Luks Smolec

theme:
  favicon: assets/icon.png
  logo: assets/logo.png
  name: material
  custom_dir: overrides
  palette:
    primary: green
    accent: green
  font:
    text: Source Sans 3
  language: pl
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.indexes

nav:
  - 'Home': index.md
  - 'Projekt': project.md
  - 'Aleja Łuczników':
    - avenue.md
    - archers.md
  - 'Wsparcie finansowe': crowdfunding.md
  - Blog:
    - blog/index.md
  - Kontakt: contact.md

extra:
  social:
    - icon: material/run-fast
      link: https://runarchery.pl/
    - icon: material/bow-arrow
      link: https://uksluks.pl
    - icon: material/facebook
      link: https://www.facebook.com/archeryparksmolec/
    - icon: material/instagram
      link: https://www.instagram.com/smoleckiparkluczniczy/
    - icon: material/robot
      link: https://stats.uptimerobot.com/u3PRmM31ye/797062699
  analytics:
    provider: google
    property: G-CZBYDQ2SBQ
  consent:
    title: Dbamy o Twoją prywatność
    description: >- 
      Używamy plików cookie również do rozpoznawania Twoich powtarzających się wizyt i preferencji
      co do pomiaru efektywności naszej storny i tego, czy użytkownicy znaleźć to, czego szukają. Za Twoją zgodą pomagasz nam ulepszyć naszą stronę.
    actions:
      - accept
      - manage

plugins:
  - search  
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: pl
          default: true
          name: Polski
          build: true
        - locale: en
          name: English
          build: true          
          nav_translations:
            Home: Home
            Projekt: Project
            Aleja Łuczników: Archers Avenue
            Wsparcie finansowe: Financial Support
            Blog: Blog
            Kontakt: Contact
        - locale: de
          name: Deutsch
          build: true
          nav_translations:
            Home: Home
            Projekt: Projekt
            Aleja Łuczników: Bogenschützen Allee
            Wsparcie finansowe: Finanzielle Unterstützung
            Blog: Blog
            Kontakt: Kontakt
  - blog:
      pagination_per_page: 5
      draft_on_serve: false
      draft_if_future_date: true
      blog_toc: true
  - tags:
      tags_file: tags.md
  - glightbox:
      zoomable: true
      effect: zoom
      touchNavigation: true
  - rss:
      match_path: blog/.*
      date_from_meta:
        as_creation: date
      use_git: false
  - social
  - autorefs:
      resolve_closest: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
