authors:
  kamil:
    name: Kamil Ściana
    description: Członek zarządu UKS Luks Smolec
    avatar: assets/kamil.png
  przemek:
    name: Przemysław Jastrząb
    description: Prezes UKS Luks Smolec
    avatar: assets/przemek.jpg
  sebastian:
    name: Sebastian Kotlarz
    description: historyk i zaangażowany mieszkaniec Smolca
    avatar: assets/sebastian-kotlarz.jpg
    url: https://patronite.pl/sebastiankotlarz/media