authors:
  kamil:
    name: Kamil Ściana
    description: Członek zarządu UKS Luks Smolec
    avatar: assets/kamil.png
  przemek:
    name: Przemysław Jastrząb
    description: Prezes UKS Luks Smolec
    avatar: assets/przemek.jpg